Cysharp/ZLinq

- src/ZLinq.SourceGenerator/ZLinq.SourceGenerator.csproj
- src/ZLinq.__Unity/ZLinq.__Unity.csproj
- src/ZLinq/ZLinq.csproj
When build solution with Visual Studio.
Following messages are displayed on Output Window.
> FastUpToDate: This project has enabled build acceleration, but not all referenced projects produce a reference assembly.
> Ensure projects producing the following outputs have the 'ProduceReferenceAssembly' MSBuild property set to 'true': 
So I've added `ProduceReferenceAssembly` setting for NetStandard targets.
Note: `ProduceReferenceAssembly` is [enabled by default on .NET 5 or later.](https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md#configuration)
But it's not enabled on NetStandard2.0/2.1 for backward compatibility reason.
> chore: Add MSBuild settings for VS build acceleration

- Directory.Build.props
- sandbox/Benchmark/Benchmark.csproj
- sandbox/Benchmark/Benchmarks/SimdAny.cs
- src/ZLinq/ZLinq.csproj
- tests/ZLinq.Tests/Linq/CountByTest.cs
- tests/ZLinq.Tests/ZLinq.Tests.csproj
Currently tests/benchmarks project is targetting .NET 9 only.
This PR add support for .NET8, and .NET 10 (Currently preview.2)
Note: .NET 10 support is added when using Visual Studio **Preview** version only.
I'll not affect other build environment.
Additionally, following changes included.
- Add settings to suppress message when using preview version of .NET SDK
- Suppress CS8002 warnings on benchmark project
- Fix test/benchmark code that can't build with .NET 8
> chore: Add support for multiple target frameworks

- src/ZLinq.DropInGenerator/DropInGenerator.cs
This PR intended to fix CRLF/LF mixed source files issues on some environment.
> chore: Fix mixed line endings of source generated files

- tests/ZLinq.Tests/Linq/ChunkTest.cs
- tests/ZLinq.Tests/Linq/OrderByTest.cs
- tests/ZLinq.Tests/ZLinq.Tests.csproj
This PR contains following changes
- Add `net6.0` to TargetFrameworks. It's used for `netstandard2.1` tests.
- Fix some tests that failed on `net6.0`
- Update xUnit.v3 package to `2.0.0`.  
` net6.0` support is dropped from `2.0.0`. So need to add conditional `PackageReference`. 
- Drop VSTest related package references.  
`,slnx` supported VS versions also supports `Microsoft.Testing.Platform` based tests.
> chore: Add .NET 6 target for netstandard2.1 tests & update xUnit.v3 package version to 2.0.0

- .github/codecov.yml
- .github/workflows/build-debug.yml
- tests/codecoverage.runsettings
This PR add code coverage related settings to generate report by using [Codecov](https://about.codecov.io/).
This PR don't affects `Cysharp/ZLinq` repository unless explicitly set `secrets.CODECOV_TOKEN` on repository.
Following coverage report is generated by my forked repository's workflow.
https://app.codecov.io/github/filzrev/ZLinq
**`.github/codecov.yml`**
CodeCov setting file.
It's placed to suppress comment to PR. (To avoid delayed notifications)
**`.github/workflows/build-debug.yml`**
Modify CI workflow settings and add following jobs
- Check `secrets.CODECOV_TOKEN` existing
- Collect CodeCoverage and send report to CodeCov (It's run only when `secrets.CODECOV_TOKEN` exists)
**`tests/codecoverage.runsettings`**
Setting file for code coverage.
> chore: Add codecov coverage settings

- tests/System.Linq.Tests/System.Linq.Tests.csproj
- tests/ZLinq.Tests/ZLinq.Tests.csproj
Currently it can't confirms what's unit tests failed on CI.
Because `Microsoft.Testing.Platform` output logs to file and it's not uploaded as artifacts.
This PR add following setting to output error logs to console. 
```xml
<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
```
> chore: Show unit tests errors on CI logs

- sandbox/ConsoleApp/Program.cs
- src/ZLinq/Linq/ToLookup.cs
This PR add `DebuggerTypeProxy` for `Grouping` and `Lookup`.
DebuggerTypeProxy behaviors can be confirmed by code that added to `sandbox/ConsoleApp/Program.cs`
> chore: add DebuggerTypeProxy for Grouping/Lookup

- sandbox/Benchmark/Benchmarks/Net80OptimizedBenchmark.cs
- sandbox/Benchmark/Benchmarks/Net90OptimizedBenchmark.cs
This PR add LINQ benchmarks that described at following URLs.
- https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8
- https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-9
From benchmark results.
Some dedicated optimization path seems to be used by System.Linq.
**Results of Net80OptimizedBenchmark**
| Method                           | Mean        | Error     | StdDev    | Gen0   | Allocated |
|--------------------------------- |------------:|----------:|----------:|-------:|----------:|
| SelectToList_SystemLinq          |   811.08 ns | 426.81 ns | 23.395 ns | 0.9804 |   4.01 KB |
| RepeatToList_SystemLinq          |    58.63 ns |  77.59 ns |  4.253 ns | 0.2658 |   1.09 KB |
| RangeSelectToList_SystemLinq     |   775.82 ns | 715.34 ns | 39.210 ns | …
> chore: Add benchmarks that use dedicated optimization path by System.Linq

- src/ZLinq/Linq/Index.cs
This PR fix issue that following **stress test** failed.
https://github.com/Cysharp/ZLinq/blob/057eafb7e46a477bf24e077daa45e142bf8f1292/tests/System.Linq.Tests/Tests/ZLinq/IndexTests.cs#L39-L51
It need to change base index to `-1` to support enumerable that length is int.MaxLength.
**System.Linq implementation**
https://github.com/dotnet/runtime/blob/a2e1d21bb4faf914363968b812c990329ba92d8e/src/libraries/System.Linq/src/System/Linq/Index.cs#L30-L42
> chore: fix Index() issue for enumerable that length is int.MaxValue

- Directory.Build.props
- src/ZLinq.__Unity/ZLinq.__Unity.csproj
- src/ZLinq/ZLinq.csproj
- tests/System.Linq.Tests/System.Linq.Tests.csproj
- tests/ZLinq.Tests/ZLinq.Tests.csproj
This PR contains following changes.
Because It's included by default on .NET SDK 8 or later version.
- System.Buffers
- System.Memory
- System.Runtime.CompilerServices.Unsafe
- xunit.v3
> chore: Update NuGet package versions

- Directory.Build.props
When build solution with .NET 10 SDK Preview2.
Following warnings are reported and handled as error.
> The 'scoped' modifier of parameter 'span' doesn't match overridden or implemented member.
- https://github.com/Cysharp/ZLinq/blob/057eafb7e46a477bf24e077daa45e142bf8f1292/src/ZLinq.Unity/Assets/ZLinq.Unity/Runtime/OfComponent.cs#L27
- https://github.com/Cysharp/ZLinq/blob/057eafb7e46a477bf24e077daa45e142bf8f1292/src/ZLinq.Unity/Assets/ZLinq.Unity/Runtime/OfComponent.cs#L78
> chore: exclude CS9074 warning from WaningAsError

- tests/ZLinq.Tests/Linq/AsValueEnumerableTest.cs
- tests/ZLinq.Tests/Linq/EmptyTest.cs
- tests/ZLinq.Tests/Linq/FromImmutableArrayTest.cs
- tests/ZLinq.Tests/Linq/FromReadOnlySequenceTest.cs
- tests/ZLinq.Tests/Linq/FromSpanTest.cs
- tests/ZLinq.Tests/ZLinq.Tests.csproj
This PR add unit tests for following APIs.
- FromEmpty
- FromImmutableArray
- FromReadOnlySequenceTest
- FromSpanTest
By these changes. Code coverage rate increased from 82.91% to 83.86%
Additionally, I've added `AllowUnsafeBlocks` to `ZLinq.Tests.csproj`.
It's required to check `Span` equity.
> chore: Add tests to increase code coverage rate

- src/ZLinq/Linq/Contains.cs
- src/ZLinq/Simd/Vectorizable.cs
This PR add custom code path for .NET 10 that use `Span.Contains` API.
Currently CI don't run .NET 10 tests.
So I've confirmed it works as expected on local environment.
> chore: Add custom code path for .NET 10 that use  `Span.Contains` API 

- sandbox/Benchmark/Benchmarks/VectorizableUpdate.cs
The benchmarking of VectorizableUpdate.For was not fair.
```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.26100.3476)
13th Gen Intel Core i7-13700F, 1 CPU, 24 logical and 16 physical cores
.NET SDK 9.0.200
[Host]            : .NET 9.0.3 (9.0.325.11113), X64 RyuJIT AVX2
Default(.NET 9.0) : .NET 9.0.3 (9.0.325.11113), X64 RyuJIT AVX2
Job=Default(.NET 9.0)  PowerPlanMode=00000000-0000-0000-0000-000000000000  Toolchain=.NET 9.0  
IterationCount=3  LaunchCount=1  RunStrategy=Throughput  
WarmupCount=3  
| Method           | N     | Mean       | Error     | StdDev   | Allocated |
|----------------- |------ |-----------:|----------:|---------:|----------:|
| For              | 10000 | 3,912.5 ns | 360.14 ns | 19.74 ns |         - |
| 'For (PR)'       | 10000 | 2,768.7 ns | 190.00 ns | 10.41 ns | …
```
> chore: Fair benchmarking of VectorizableUpdate.

- src/ZLinq/Linq/Append.cs
- src/ZLinq/Linq/Prepend.cs
There was a difference in results between Linq and ZLinq in the following edge case.
```csharp
var intMaxSequence = Enumerable.Range(0, int.MaxValue); 
var countForLinq = intMaxSequence.Append(1).LongCount();                        //  2147483648
var countForZLinq = intMaxSequence.AsValueEnumerable().Append(1).LongCount();   // -2147483648
var countForLinq2 = intMaxSequence.Prepend(1).LongCount();                      //  2147483648
var countForZLinq2 = intMaxSequence.AsValueEnumerable().Prepend(1).LongCount(); // -2147483648
```
The cause was that `TryGetNonEnumeratedCount` for `Append` and `Prepend` exceeded int.MaxValue, so I added a process to check if the count is less than `int.MaxValue`.
```csharp
public bool TryGetNonEnumeratedCount(out int count)
{
if …
```
> Fix Append and Prepend

- .editorconfig
- Directory.Build.props
- sandbox/.editorconfig
- tests/.editorconfig
This PR contains following changes.
When editing source code on local environment.
I thought It's better that warnings are shown as is.
If there is a need to simulate CI build. it can be confirmed by manually add `/p:ContinuousIntegrationBuild=true` parameter.
This rule seems to cause defensive-copy of mutable-struct.
So suppress this rule on solution level. 
This rule is not matched on current solution structure.
So suppress this rule on solution level. 
Suppress this rule on sandbox projects.
Suppress these rules on test projects.
> Chore modify analyzer settings

- sandbox/Benchmark/Benchmarks/ShuffleBench.cs
- src/ZLinq/Internal/RandomShared.cs
- src/ZLinq/Linq/Shuffle.SkipShuffle.cs
- src/ZLinq/Linq/Shuffle.cs
- tests/ZLinq.Tests/Linq/ShuffleSkipTest.cs
Similar optimization to order and take/skip combo.
`shuffle().take()` will compacting enumerator connection from:
- array -> shuffle -> take
to:
- array -> skipShuffle
intermediate shuffle will be hidden orphan branch, but it will never take internal buffer until consumed so it won't be a problem.
Add .NET 10.0 as a target and the following code at the beginning of Main().
```cs
BenchmarkRunner.Run(typeof(ShuffleBench));
return 0;
```
Then, set build target to `net10.0` and go ahead.
| Method          | N      | M      | Mean         | Error        | StdDev       |
|---------------- |------- |------- |-------------:|-------------:|-------------:|
| ShuffleTakeLinq | 1000   | 10     |   3,560.3 ns |     16.58 ns |     14.69 ns |
| ShuffleTakeLinq | 1000   | 100    |   5,853.1 ns | …
> perf: Shuffle followed by Take/Skip/TakeLast/SkipLast

- sandbox/Benchmark/BenchmarkDotNet/BenchmarkConfigs/BaseBenchmarkConfig.cs
- sandbox/Benchmark/BenchmarkDotNet/EventProcessors/BenchmarkEventProcessor.cs
- sandbox/Benchmark/BenchmarkDotNet/ExtensionMethods/ConsumerExtensions.cs
- sandbox/Benchmark/BenchmarkDotNet/ExtensionMethods/ExtensionMethods.cs
- sandbox/Benchmark/BenchmarkDotNet/ExtensionMethods/SummariesExtensions.cs
- sandbox/Benchmark/Benchmarks/SelectFromSourceTypes.cs
- sandbox/Benchmark/Properties/launchSettings.json
This PR intended to fix `ValueEnumerable::Consume` extension method performance.
Currently Consume extension accepts `IValueEnumerator<T>`.
But when using this abstraction. `TryGetNext` is invoked with `callvirt`.
And it slightly run slower. And affect ZLinq benchmarks results.
This PR include following changes.
1. Add Consume extension methods per ValueEnumerable types to optimize performance.
2. Add `[Obsolete]` attribute to existing `IValueEnumerator<T>` based extension method.
After this PR applied.
ZLinqSelect benchmark result has similar performance to ZLinq_ConsumeDirect.
(When using `IValueEnumerator<T>` based extension method. `ZLinqSelect` takes about `115.66 ms`)
**Benchmark Results: SelectFromSourceTypes<String>**
| Method                     | Mean     | Error     | StdDev …
> chore: Fix consume extension method performance

- README.md
This PR add following badges to `README.md`
1. CI Build workflow status
2. Benchmark workflow status
3. NuGet published package link
4. [DeepWiki](https://deepwiki.com/Cysharp/ZLinq) link
[![CI](https://github.com/Cysharp/ZLinq/actions/workflows/build-debug.yml/badge.svg)](https://github.com/Cysharp/ZLinq/actions/workflows/build-debug.yml)
[![Benchmark](https://github.com/Cysharp/ZLinq/actions/workflows/benchmark.yml/badge.svg)](https://github.com/Cysharp/ZLinq/actions/workflows/benchmark.yml)
[![NuGet](https://img.shields.io/nuget/v/ZLinq)](https://www.nuget.org/packages/ZLinq)
[![DeepWiki](https://img.shields.io/badge/Chat%20with-DeepWiki%20🤖-blue)](https://deepwiki.com/Cysharp/ZLinq)
> chore: Add badges to readme

- sandbox/Benchmark/Benchmarks/AllAnyPredicateWithCapturedLambda.cs
- src/ZLinq/Linq/LongCount.cs
I have made the same changes to `LongCount` as to `Count`  in v1.4.2.
Please check if it looks good.
> Improve LongCount(predicate) from array performance

- src/ZLinq/Internal/SegmentedArrayProvider.cs
This PR fix build error when using .NET 10 preview4 (It's occurred only when using Visual Studio Preview)
It's caused because .NET 10 preview4 or later contains build-in `InlineArray16<T>` implementation.
So It need to exclude ZLinq's `InlineArray16<T>`  implementation for .NET10 build.
---
Additionally .NET 10 preview 4 add following methods for FrozenCollection.
- [FrozenDictionary.Create](https://learn.microsoft.com/en-us/dotnet/api/system.collections.frozen.frozendictionary.create)
- [FrozenSet.Create](https://learn.microsoft.com/en-us/dotnet/api/system.collections.frozen.frozenset.create)
As far as I've confirmed.
These methods are simple wrapper and no performance benefits to use these methods.
**Example Code**
```csharp
public static FrozenSet<TSource> ToFrozenSet<TEnumerator, …
```
> chore: fix build for .NET 10 preview4

- .github/workflows/benchmark.yaml
- sandbox/Benchmark/Benchmarks/ZLinq/MicroBenchmarks/BinaryOperations/ConcatBenchmark.cs
- sandbox/Benchmark/Benchmarks/ZLinq/MicroBenchmarks/Sinks/CountByBenchmark.cs
- sandbox/Benchmark/README.md
- sandbox/Benchmark/TestData/TestDataGenerator.cs
This PR intended to fix benchmark reports issues on [latest benchmark](https://github.com/Cysharp/ZLinq/actions/runs/15100363106)
that some tables are not correctly shown as table format.
**What's changed in this PR**
- Add code to exclude `reports.md` (This file is expected to be used for publishing standalone report to GitHub Pages)
- Fix header/content to show correct benchmark name when using generics.
- Remove redundant benchmark from  `ConcatBenchmark.cs`
- Adjust renamed benchmark workflow name
- Cleanup code (Remove unused parameter/fix wrong class name)
> chore: Fix benchmark report

- sandbox/Benchmark/BenchmarkDotNet/ExtensionMethods/ConsumerExtensions.UnaryOperations.cs
- sandbox/Benchmark/Benchmarks/StringJoinBenchmark.cs
- sandbox/Benchmark/Benchmarks/WhereBenchmark.cs
- sandbox/Benchmark/Benchmarks/WhereSelectBenchmark.cs
**What's changed in this PR**
1. Add following benchmarks.
- `WhereBenchmark<T>`  
- `WhereSelectBenchmark<T>`
2. Modify `StringJoinBenchmark.cs` to tests several data patterns (`int` and `string`)
3. Add additional Consume methods to `ConsumerExtensions.UnaryOperations.cs`
**Background**
I've confirmed perf issue that is reported by #156.
And it seems ZLinq run slower when following conditions are met.
- Using `List<T>` as data source.
- `T` is reference type. (e.g. string)
-  Running on `.NET 8`
**Benchmark Results**
| Method          | Job    | N       | Mean      | Error     | StdDev    | Ratio | Allocated | Alloc Ratio |
|---------------- |------- |-------- |----------:|----------:|----------:|------:|----------:|------------:|
| FromArray_Linq  | .NET 8 | 1000000 |  7.083 ms | …
> chore: Add additional benchmarks

- sandbox/Benchmark/Benchmark.csproj
- sandbox/ConsoleApp/ConsoleApp.csproj
- src/ZLinq.Json/ZLinq.Json.csproj
- src/ZLinq/ZLinq.csproj
- tests/ZLinq.Tests/ZLinq.Tests.csproj
This PR update ZLinq dependent package versions.
By this PR changes.
It can write benchmarks that targeting for `.NET 10`. (e.g. https://github.com/davepcallan/dotnet10Benchmarks/tree/master/dotnet10Benchmarks)
> chore: Update ZLinq package dependencies

- src/ZLinq/Linq/AsValueEnumerable.cs
- src/ZLinq/Linq/Contains.cs
- tests/ZLinq.Tests/Linq/AsValueEnumerableTest.cs
This PR adds `AsValueEnumerable` support for `ImmutableHashSet<T>`, following the same pattern as implemented in v1.4.10.
> Add ImmutableHashSet.AsValueEnumerable

- sandbox/Benchmark/Benchmarks/TakeRangeBench.cs
- src/ZLinq/Linq/Take.cs
```
| Method                                   | N       | Mean          | Error         | StdDev        | Gen0     | Gen1     | Gen2     | Allocated |
|----------------------------------------- |-------- |--------------:|--------------:|--------------:|---------:|---------:|---------:|----------:|
| FromArray_Linq                           | 1000000 |  5,521.188 us |  6,292.783 us |   344.9287 us |        - |        - |        - |     136 B |
| FromArray_ZLinq                          | 1000000 |  2,456.492 us |  9,128.028 us |   500.3380 us |        - |        - |        - |         - |
| FromArray_ZLinqPR                        | 1000000 |  1,899.951 us |  3,019.385 us |   165.5027 us |        - |        - |        - |         - |
|
| FromEnumerable_WithTake_Linq             | 1000000 …
```
> Improve TakeRange performance

- sandbox/Benchmark/Benchmarks/TakeRangeBench.cs
- sandbox/Benchmark/TestData/BenchmarkBase/EnumerableBenchmarkBase.cs
- sandbox/Benchmark/TestData/BenchmarkBase/EnumerableBenchmarkBase_WithBasicTypes.cs
This PR fix build error when running benchmarks with `SystemLinq` config.
By modifying `EnumerableBenchmarkBase` namespace from `Benchmark.ZLinq` to `Benchmark` namespace.
**Background**
When running benchmark with `SystemLinq` config.
It replace `AsValueEnumerable()` extension method to stub implementation that returns `IEnumerable<T>`
https://github.com/Cysharp/ZLinq/blob/124885e3b63d0baca332ee59f688d57f569a304f/sandbox/Benchmark/ExtensionMethods/ValueEnumerableExtensions.SystemLinq.cs
To running benchmarks with `SystemLinq` benchmarks.
Benchmark code must be defined under `Benchmark.ZLinq` namespace.
If other namespace benchmarks use `using Benchmark.ZLinq` statement.
It cause conflict with ZLinq's `AsValueEnumerable`.
> chore: fix build error when running System.Linq benchmarks

- .github/workflows/benchmark_on_release.yaml
This PR add  `benchmark_on_release.yaml` workflow.
It's runs on `released` trigger.
And invoke following benchmarks workflows (with using .NET 10 SDK)
- `Default`
- `NuGetVersions`
- `SystemLinq`
- `TargetFrameworks`
> chore: Add `benchmark_on_release.yaml` workflow

- sandbox/Benchmark/Benchmarks/TakeLastBenchmark.cs
- sandbox/Benchmark/Properties/launchSettings.json
- src/ZLinq/Internal/RentedRingBuffer.cs
- src/ZLinq/Internal/ValueRingBuffer.cs
- src/ZLinq/Linq/TakeLast.cs
#204 
Simple TakeLast(100) Benchmark.
I wonder if optimization by TryGetSpan is needed.
(In fact, it might have been better if ValueEnumerable had an InnerSkip functionality)
| Method                  | N       | Mean           | Error          | StdDev       | Gen0   | Allocated |
|------------------------ |-------- |---------------:|---------------:|-------------:|-------:|----------:|
| FromArray_Linq          | 1000000 |       228.8 ns |       33.15 ns |      1.82 ns | 0.0086 |     136 B |
| FromArray_ZLinq         | 1000000 | 3,547,090.8 ns |  171,427.16 ns |  9,396.50 ns |      - |      48 B |
| FromArray_ZLinq(PR)     | 1000000 |   469,546.8 ns |  162,486.33 ns |  8,906.42 ns |      - |         - |
|                         |         |                |                | …
> Implement TakeLast performance optimizations and benchmarks

- sandbox/Benchmark/Benchmarks/ZLinq/MicroBenchmarks/Sinks/AverageBenchmark.cs
I fixed the ZLinq process for `AverageBenchmark`.
ZLinq process was performing an additional division operation (`x => x / T.CreateChecked(source.Length)`), so I removed it.
> Fix ZLinq process for `AverageBenchmark`

- .gitignore
- Directory.Build.props
- sandbox/Benchmark/Benchmark.csproj
- sandbox/ConsoleApp/ConsoleApp.csproj
- sandbox/ConsoleAppNativeAOT/ConsoleAppNativeAOT.csproj
- sandbox/ConsoleAppNet6/ConsoleAppNet6.csproj
- src/FileGen/FileGen.csproj
- src/ZLinq.DropInGenerator/ZLinq.DropInGenerator.csproj
- src/ZLinq.FileSystem/ZLinq.FileSystem.csproj
- src/ZLinq.Godot/ZLinq.Godot.csproj
- src/ZLinq.Json/ZLinq.Json.csproj
- src/ZLinq/ZLinq.csproj
- tests/System.Linq.Tests/System.Linq.Tests.csproj
- tests/ZLinq.Tests/ZLinq.Tests.csproj
Change IsPackable from default, implicitly `true`, to explicitly `false`.
This prevent unintended nuget package generation like sandbox, benchmark, and etc....
Side effect:
- nupkg csproj required to specify `<IsPackable>true</IsPackable>`. Previously they are omitted.
- LICENSE.md is now handled by Directory.Build.props
> chore: Specify IsPackable=false on Directory.Build.props, explicitly true for target packages.

- tests/System.Linq.Tests/SkipReason.cs
- tests/System.Linq.Tests/Tests/System.Linq/CountTests.cs
- tests/System.Linq.Tests/Tests/System.Linq/MinTests.cs
- tests/System.Linq.Tests/Tests/System.Linq/OrderedSubsetting.cs
- tests/System.Linq.Tests/Tests/System.Linq/RangeTests.cs
- tests/System.Linq.Tests/Tests/System.Linq/SelectTests.cs
- tests/System.Linq.Tests/Tests/System.Linq/SequenceTests.cs
- tests/System.Linq.Tests/Tests/System.Linq/TakeTests.cs
- tests/System.Linq.Tests/Tests/ZLinq/MinTests.cs
- tests/System.Linq.Tests/Tests/ZLinq/SelectTests.cs
This PR update `System.Linq` compatibility tests based on latest code.
https://github.com/dotnet/runtime/commits/main/src/libraries/System.Linq/tests
**1. SkipReason.cs**
Fix test skip message.
**2. CountTests.cs**
Modify test code based on .NET 10 RC1
**3. MinTests.cs**
Fix typo.
**4. OrderedSubsetting.cs**
**5. RangeTests.cs**
**6. TakeTests.cs**
**7. SequenceTests.cs**
Modify test code based on .NET 10 RC1
**8. SelectTests.cs**
Add `SelectSideEffectsExecutedOnCount` test code.
This test is skipped on ZLinq.
Because ZLinq seems not allow side-effect inside LINQ query.
> chore: Update System.Linq compatibility tests

- Directory.Build.props
- sandbox/Benchmark/Benchmark.csproj
- sandbox/ConsoleApp/ConsoleApp.csproj
- sandbox/ConsoleAppNet6/ConsoleAppNet6.csproj
- src/FileGen/FileGen.csproj
- src/ZLinq.Json/ZLinq.Json.csproj
- src/ZLinq/Linq/JoinToString.cs
- src/ZLinq/ZLinq.csproj
- tests/System.Linq.Tests/Stubs/xUnit/ConditionalFactAttribute.cs
- tests/System.Linq.Tests/Stubs/xUnit/ConditionalTheoryAttribute.cs
- tests/System.Linq.Tests/System.Linq.Tests.csproj
- tests/ZLinq.Tests/ZLinq.Tests.csproj
This PR contains following changes
**1. Update package dependencies to latest version**
**2. Remove `CS9074` warning suppressions**
It's added by #118.
But It's not happens when build project with .NET 10 RC1.
**3. Add `CheckEolTargetFramework` setting for project that using .NET 6**
It's required to suppress `NETSDK1138` warnings.
**4. Modify `FastAllocateString` method signature for .NET 10 or later.**
It's required because some tests of `JoinToStringTest` failed with following error when running on .NET 10 RC1
> System.MissingMethodException : Method not found: 'System.String.FastAllocateString'.
**5. Modify `ConditionalTheory`/`ConditionalFact` attribute constructor**
It's required to suppress [xUnit3003](https://xunit.net/xunit.analyzers/rules/xUnit3003.html) warnings.
I've confirmed …
> chore: Update package dependencies and modify code to support .NET 10
